MACRO (ADD_COMPARE_TEST TARGET_NAME)
     SET(MY_GL_NAME "MyGLTest${TARGET_NAME}")
     ADD_EXECUTABLE(${MY_GL_NAME} "${MY_GL_NAME}.cpp")
     TARGET_LINK_LIBRARIES(${MY_GL_NAME} Export)
     ADD_TEST("${TARGET_NAME}TestMyGL" ${MY_GL_NAME})


     SET(GLUT_TEST_NAME "GlutTest${TARGET_NAME}")
     ADD_EXECUTABLE(${GLUT_TEST_NAME} "${GLUT_TEST_NAME}.cpp")
     TARGET_LINK_LIBRARIES(${GLUT_TEST_NAME} 
	  GlutInit
	  ${GLEW_LIBRARY} ${GLUT_LIBRARIES} ${OPENGL_LIBRARIES})
     ADD_TEST("${TARGET_NAME}TestGlut" ${GLUT_TEST_NAME})
ENDMACRO()

